# Copyright (C) 2025 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: End svtrace
  command:
      killall --wait "svtrace.py" --signal SIGINT
- name: Fetch svtrace result file
  ansible.builtin.fetch:
    src: /tmp/results
    dest: "{{ playbook_dir }}/../tests_results/latency/hyp_svtrace.record"
    flat: true
